import {
  type RouteConfig,
  index,
  layout,
  route,
} from "@react-router/dev/routes";

export default [
  index("routes/landing.tsx"),
  route("splash", "routes/splash.tsx"),
  route("chinh-sach-bao-mat", "routes/chinh-sach-bao-mat.tsx"),
  route("dieu-khoan", "routes/dieu-khoan.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("x/:token", "routes/x.$token.tsx"),
  route("share/:token", "routes/share.$token.tsx"),
  route("ngay/:ngay", "routes/ngay.$ngay.tsx"),
  route("auth/callback", "routes/auth.callback.tsx"),
  route("dang-nhap", "routes/dang-nhap.tsx"),
  route("dang-nhap/email", "routes/dang-nhap.email.tsx"),
  route("dang-ky", "routes/dang-ky.tsx"),
  route("quen-mat-khau", "routes/quen-mat-khau.tsx"),
  route("quen-mat-khau/da-gui", "routes/quen-mat-khau.da-gui.tsx"),
  route("dat-lai-mat-khau/:token", "routes/dat-lai-mat-khau.$token.tsx"),

  layout("routes/authenticated.tsx", [
    route("lich", "routes/lich.tsx"),
    route("lich/thang", "routes/lich.thang.tsx"),
    route("tra-cuu", "routes/tra-cuu.tsx"),
    route("tra-cuu/ket-qua", "routes/tra-cuu.ket-qua.tsx"),
    route("tra-cuu/dang-tim", "routes/tra-cuu.dang-tim.tsx"),
    route("tra-cuu/khong-co-ngay", "routes/tra-cuu.khong-co-ngay.tsx"),
    route("tra-cuu/hop-tuoi", "routes/tra-cuu.hop-tuoi.tsx"),
    route("tra-cuu/hop-tuoi/ket-qua", "routes/tra-cuu.hop-tuoi.ket-qua.tsx"),
    route("toi", "routes/toi.tsx"),
    route("toi/sua-ho-so", "routes/toi.sua-ho-so.tsx"),
    route("toi/cai-dat", "routes/toi.cai-dat.tsx"),
    route("toi/la-so", "routes/toi.la-so.tsx"),
    route("toi/luan-bat-tu", "routes/toi.luan-bat-tu.tsx"),
    route("toi/luan-tieu-van", "routes/toi.luan-tieu-van.tsx"),
    route("toi/so-viec", "routes/toi.so-viec.tsx"),
    route("gio-sinh", "routes/gio-sinh.tsx"),
    route("dang-dung-lich", "routes/dang-dung-lich.tsx"),
    route("lich-da-mo", "routes/lich-da-mo.tsx"),
    route("dat-lich", "routes/dat-lich.tsx"),
    route("dat-lich/xac-nhan", "routes/dat-lich.xac-nhan.tsx"),
    route("dat-lich/that-bai", "routes/dat-lich.that-bai.tsx"),
    route("thanh-cong", "routes/thanh-cong.tsx"),
    route("luan/mua/xac-nhan", "routes/luan.mua.xac-nhan.tsx"),
    route("luan/mua/thanh-cong", "routes/luan.mua.thanh-cong.tsx"),
    route("luan/mua/that-bai", "routes/luan.mua.that-bai.tsx"),
    route("luan-ai/:context", "routes/luan-ai.$context.tsx"),
    route("luan-ai/:context/day-du", "routes/luan-ai.$context.day-du.tsx"),
    route("tien-ich/chuyen-lich", "routes/tien-ich.chuyen-lich.tsx"),
    route("tien-ich/phong-thuy", "routes/tien-ich.phong-thuy.tsx"),
    route("offline", "routes/offline.tsx"),
  ]),

  /** Legacy /app/* — parent redirects to Direction C (see app.tsx + nav-config). */
  route("app/*", "routes/app.tsx"),
] satisfies RouteConfig;
