import {
  type RouteConfig,
  index,
  layout,
  route,
} from "@react-router/dev/routes";

export default [
  index("routes/landing.tsx"),
  route("splash", "routes/splash.tsx"),
  route("chinh-sach-bao-mat", "routes/chinh-sach-bao-mat.tsx"),
  route("dieu-khoan", "routes/dieu-khoan.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("terms", "routes/terms.tsx"),
  route("x/:token", "routes/x.$token.tsx"),
  route("share/:token", "routes/share.$token.tsx"),
  route("auth/callback", "routes/auth.callback.tsx"),
  route("dang-nhap", "routes/dang-nhap.tsx"),
  route("dang-nhap/email", "routes/dang-nhap.email.tsx"),
  route("dang-ky", "routes/dang-ky.tsx"),
  route("quen-mat-khau", "routes/quen-mat-khau.tsx"),
  route("quen-mat-khau/da-gui", "routes/quen-mat-khau.da-gui.tsx"),
  route("dat-lai-mat-khau/:token", "routes/dat-lai-mat-khau.$token.tsx"),

  layout("routes/authenticated.tsx", [
    route("lich", "routes/lich.tsx"),
    route("lich/thang", "routes/lich.thang.tsx"),
    route("ngay/:ngay", "routes/ngay.$ngay.tsx"),
    route("tra-cuu", "routes/tra-cuu.tsx"),
    route("tra-cuu/ket-qua", "routes/tra-cuu.ket-qua.tsx"),
    route("tra-cuu/hop-tuoi", "routes/tra-cuu.hop-tuoi.tsx"),
    route("tra-cuu/hop-tuoi/ket-qua", "routes/tra-cuu.hop-tuoi.ket-qua.tsx"),
    route("toi", "routes/toi.tsx"),
    route("toi/sua-ho-so", "routes/toi.sua-ho-so.tsx"),
    route("toi/cai-dat", "routes/toi.cai-dat.tsx"),
    route("toi/la-so", "routes/toi.la-so.tsx"),
    route("toi/luan-bat-tu", "routes/toi.luan-bat-tu.tsx"),
    route("gio-sinh", "routes/gio-sinh.tsx"),
    route("dang-dung-lich", "routes/dang-dung-lich.tsx"),
    route("lich-da-mo", "routes/lich-da-mo.tsx"),
    route("dat-lich", "routes/dat-lich.tsx"),
    route("dat-lich/xac-nhan", "routes/dat-lich.xac-nhan.tsx"),
    route("thanh-cong", "routes/thanh-cong.tsx"),
    route("luan/mua/xac-nhan", "routes/luan.mua.xac-nhan.tsx"),
    route("luan/mua/thanh-cong", "routes/luan.mua.thanh-cong.tsx"),
    route("luan-ai/:context", "routes/luan-ai.$context.tsx"),
    route("luan-ai/:context/day-du", "routes/luan-ai.$context.day-du.tsx"),
    route("tien-ich/chuyen-lich", "routes/tien-ich.chuyen-lich.tsx"),
    route("offline", "routes/offline.tsx"),
  ]),

  route("app", "routes/app.tsx", [
    index("routes/app._index.tsx"),
    route("home", "routes/app.home.tsx"),
    route("nhip/lich-su", "routes/app.nhip.lich-su.tsx"),
    route("nhip/cai-dat", "routes/app.nhip.cai-dat.tsx"),
    route("hom-nay", "routes/app.hom-nay.tsx"),
    route("tuan-nay", "routes/app.tuan-nay.tsx"),
    route("chon-ngay", "routes/app.chon-ngay.tsx"),
    route("chon-ngay/ket-qua", "routes/app.chon-ngay.ket-qua.tsx"),
    route("loi/khong-tim-thay-ngay", "routes/app.loi.khong-tim-thay-ngay.tsx"),
    route("thang", "routes/app.thang.tsx"),
    route("toi", "routes/app.toi.tsx"),
    route("tra-cuu", "routes/app.tra-cuu.tsx"),
    route("so-viec", "routes/app.so-viec.tsx"),
    route("chuyen-lich", "routes/app.chuyen-lich.tsx"),
    route("tieu-van", "routes/app.tieu-van.tsx"),
    route("lich-thang", "routes/app.lich-thang.tsx"),
    route("ngay/:ngay", "routes/app.ngay.$ngay.tsx"),
    route("la-so", "routes/app.la-so.tsx"),
    route("la-so/chi-tiet", "routes/app.la-so.chi-tiet.tsx"),
    route("van-thang", "routes/app.van-thang.tsx"),
    route("bat-dau", "routes/app.bat-dau.tsx"),
    route("mua-luong", "routes/app.mua-luong.tsx"),
    route("mua-luong/thanh-cong", "routes/app.mua-luong.thanh-cong.tsx"),
    route("cai-dat", "routes/app.cai-dat.tsx"),
    route("cai-dat-app", "routes/app.cai-dat-app.tsx"),
    route("hop-tuoi", "routes/app.hop-tuoi.tsx"),
    route("phong-thuy", "routes/app.phong-thuy.tsx"),
    route("chia-se", "routes/app.chia-se.tsx"),
    route("thong-bao-quyen", "routes/app.thong-bao-quyen.tsx"),
  ]),
] satisfies RouteConfig;
